Fail
file path is :
projects/deltachat-core/rust/src/location.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error: cannot find macro `goto_cleanup` in this scope
   --> src/location.rs:353:9
    |
353 |         goto_cleanup!();
    |         ^^^^^^^^^^^^

error: cannot find macro `cleanup` in this scope
   --> src/location.rs:387:5
    |
387 |     cleanup!();
    |     ^^^^^^^

error[E0425]: cannot find value `DC_CONTEXT_MAGIC` in this scope
   --> src/location.rs:350:58
    |
350 |     if context.inner.is_null() || context.inner.magic != DC_CONTEXT_MAGIC
    |                                                          ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CONTACT_ID_SELF` in this scope
   --> src/location.rs:374:21
    |
374 |                     DC_CONTACT_ID_SELF as i64
    |                     ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CONTACT_ID_SELF` in this scope
   --> src/location.rs:383:44
    |
383 |         context.emit_location_changed(Some(DC_CONTACT_ID_SELF)).await?;
    |                                            ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `is_null` found for struct `Arc<InnerContext>` in the current scope
   --> src/location.rs:350:22
    |
350 |     if context.inner.is_null() || context.inner.magic != DC_CONTEXT_MAGIC
    |                      ^^^^^^^ method not found in `Arc<InnerContext>`

error[E0609]: no field `magic` on type `Arc<InnerContext>`
   --> src/location.rs:350:49
    |
350 |     if context.inner.is_null() || context.inner.magic != DC_CONTEXT_MAGIC
    |                                                 ^^^^^ unknown field
    |
    = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `generating_key_mutex`, `oauth2_mutex` ... and 17 others

error[E0599]: no method named `query_map` found for reference `&context::Context` in the current scope
   --> src/location.rs:356:31
    |
356 |     stmt_chats = Some(context.query_map(
    |                       --------^^^^^^^^^ method not found in `&Context`
    |
help: one of the expressions' fields has a method of the same name
    |
356 |     stmt_chats = Some(context.inner.sql.query_map(
    |                               ++++++++++
help: one of the expressions' fields has a method of the same name
    |
356 |     stmt_chats = Some(context.sql.query_map(
    |                               ++++

error[E0599]: no method named `prepare` found for reference `&context::Context` in the current scope
   --> src/location.rs:365:44
    |
365 |                 stmt_insert = Some(context.prepare(
    |                                    --------^^^^^^^ method not found in `&Context`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `prepare`, perhaps you need to implement one of them:
            candidate #1: `precis_core::profile::Profile`
            candidate #2: `precis_core::profile::PrecisFastInvocation`

error[E0599]: no method named `interrupt_location` found for reference `&context::Context` in the current scope
   --> src/location.rs:384:17
    |
384 |         context.interrupt_location().await;
    |                 ^^^^^^^^^^^^^^^^^^ method not found in `&Context`
    |
help: one of the expressions' fields has a method of the same name
    |
384 |         context.inner.scheduler.interrupt_location().await;
    |                 ++++++++++++++++
help: one of the expressions' fields has a method of the same name
    |
384 |         context.scheduler.interrupt_location().await;
    |                 ++++++++++

Some errors have detailed explanations: E0425, E0599, E0609.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `deltachat` (lib) due to 10 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `deltachat` (lib test) due to 10 previous errors
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

