Fail
file path is :
projects/deltachat-core/rust/src/chat.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/RustRepoTrans/projects/deltachat-core/rust)
error: statements are terminated with a semicolon
    --> src/chat.rs:3939:8
     |
3939 | cleanup:
     |        ^ help: use a semicolon instead: `;`

error[E0252]: the name `Result` is defined multiple times
  --> src/chat.rs:15:50
   |
6  | use anyhow::Result;
   |     -------------- previous import of the type `Result` here
...
15 | use anyhow::{anyhow, bail, ensure, Context as _, Result};
   |                                                  ^^^^^^ `Result` reimported here
   |
   = note: `Result` must be defined only once in the type namespace of this module

error[E0255]: the name `ChatId` is defined multiple times
   --> src/chat.rs:171:1
    |
5   | use crate::chat::ChatId;
    |     ------------------- previous import of the type `ChatId` here
...
171 | pub struct ChatId(u32);
    | ^^^^^^^^^^^^^^^^^^^^^^^ `ChatId` redefined here
    |
    = note: `ChatId` must be defined only once in the type namespace of this module
help: you can use `as` to change the binding name of the import
    |
5   | use crate::chat::ChatId as OtherChatId;
    |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0252]: the name `ContactId` is defined multiple times
  --> src/chat.rs:32:37
   |
4  | use crate::contact::ContactId;
   |     ------------------------- previous import of the type `ContactId` here
...
32 | use crate::contact::{self, Contact, ContactId, Origin};
   |                                     ^^^^^^^^^--
   |                                     |
   |                                     `ContactId` reimported here
   |                                     help: remove unnecessary import
   |
   = note: `ContactId` must be defined only once in the type namespace of this module

error: cannot find macro `goto_cleanup` in this scope
    --> src/chat.rs:3905:9
     |
3905 |         goto_cleanup!();
     |         ^^^^^^^^^^^^

error: cannot find macro `goto_cleanup` in this scope
    --> src/chat.rs:3909:9
     |
3909 |         goto_cleanup!();
     |         ^^^^^^^^^^^^

error: cannot find macro `goto_cleanup` in this scope
    --> src/chat.rs:3914:9
     |
3914 |         goto_cleanup!();
     |         ^^^^^^^^^^^^

error[E0425]: cannot find value `DC_CONTACT_ID_LAST_SPECIAL` in this scope
    --> src/chat.rs:3904:92
     |
3904 | ... || contact_id <= DC_CONTACT_ID_LAST_SPECIAL && contact_id != ContactId::SELF {
     |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `DC_CHAT_ID_LAST_SPECIAL`
     |
    ::: src/constants.rs:123:1
     |
123  | pub const DC_CHAT_ID_LAST_SPECIAL: ChatId = ChatId::new(9);
     | ----------------------------------------------------------- similarly named constant `DC_CHAT_ID_LAST_SPECIAL` defined here

error[E0425]: cannot find value `DC_EVENT_ERROR_SELF_NOT_IN_GROUP` in this scope
    --> src/chat.rs:3913:27
     |
3913 |         context.log_event(DC_EVENT_ERROR_SELF_NOT_IN_GROUP, 0, "Cannot remove contact from chat; self not in group.").await;
     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_MSG_TEXT` in this scope
    --> src/chat.rs:3919:26
     |
3919 |             msg.set_type(DC_MSG_TEXT);
     |                          ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_STR_MSGGROUPLEFT` in this scope
    --> src/chat.rs:3922:55
     |
3922 |                 msg.set_text(context.stock_system_msg(DC_STR_MSGGROUPLEFT, None, None, ContactId::SELF).await?);
     |                                                       ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_STR_MSGDELMEMBER` in this scope
    --> src/chat.rs:3924:55
     |
3924 |                 msg.set_text(context.stock_system_msg(DC_STR_MSGDELMEMBER, contact.addr, None, ContactId::SELF).await?);
     |                                                       ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CMD_MEMBER_REMOVED_FROM_GROUP` in this scope
    --> src/chat.rs:3926:25
     |
3926 |             msg.set_cmd(DC_CMD_MEMBER_REMOVED_FROM_GROUP);
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_EVENT_MSGS_CHANGED` in this scope
    --> src/chat.rs:3929:32
     |
3929 |             context.emit_event(DC_EVENT_MSGS_CHANGED, chat_id, msg.id).await;
     |                                ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_EVENT_CHAT_MODIFIED` in this scope
    --> src/chat.rs:3935:24
     |
3935 |     context.emit_event(DC_EVENT_CHAT_MODIFIED, chat_id, 0).await;
     |                        ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `cleanup` in this scope
    --> src/chat.rs:3939:1
     |
3939 | cleanup:
     | ^^^^^^^ not found in this scope

warning: unused import: `crate::chat::ChatId`
 --> src/chat.rs:5:5
  |
5 | use crate::chat::ChatId;
  |     ^^^^^^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:6:5
  |
6 |     unused,
  |     ^^^^^^
  = note: `#[warn(unused_imports)]` implied by `#[warn(unused)]`

warning: unused import: `anyhow::Result`
 --> src/chat.rs:6:5
  |
6 | use anyhow::Result;
  |     ^^^^^^^^^^^^^^

warning: unused import: `ContactId`
  --> src/chat.rs:32:37
   |
32 | use crate::contact::{self, Contact, ContactId, Origin};
   |                                     ^^^^^^^^^

error[E0599]: no method named `get_contact` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3899:27
     |
3899 |     let contact = context.get_contact(contact_id).await?;
     |                           ^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `chat_new` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3900:24
     |
3900 |     let chat = context.chat_new().await?;
     |                        ^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `msg_new_untyped` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3901:23
     |
3901 |     let msg = context.msg_new_untyped().await?;
     |                       ^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `is_null_or_invalid` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3904:16
     |
3904 |     if context.is_null_or_invalid() || chat_id <= DC_CHAT_ID_LAST_SPECIAL || contact_id <= DC_CONTACT_ID_LAST_SPECIAL && contact_id != Co...
     |                ^^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `real_group_exists` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3908:17
     |
3908 |     if !context.real_group_exists(chat_id).await? || !context.chat_load_from_db(chat, chat_id).await? {
     |                 ^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `chat_load_from_db` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3908:63
     |
3908 |     if !context.real_group_exists(chat_id).await? || !context.chat_load_from_db(chat, chat_id).await? {
     |                                                               ^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `is_self_in_chat` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3912:17
     |
3912 |     if !context.is_self_in_chat(chat_id).await? {
     |                 ^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `log_event` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3913:17
     |
3913 |         context.log_event(DC_EVENT_ERROR_SELF_NOT_IN_GROUP, 0, "Cannot remove contact from chat; self not in group.").await;
     |                 ^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `do_send_status_mails` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3918:20
     |
3918 |         if context.do_send_status_mails() {
     |                    ^^^^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `set_group_explicitly_left` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3921:25
     |
3921 |                 context.set_group_explicitly_left(chat.grpid).await?;
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `stock_system_msg` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3922:38
     |
3922 |                 msg.set_text(context.stock_system_msg(DC_STR_MSGGROUPLEFT, None, None, ContactId::SELF).await?);
     |                                      ^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `stock_system_msg` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3924:38
     |
3924 |                 msg.set_text(context.stock_system_msg(DC_STR_MSGDELMEMBER, contact.addr, None, ContactId::SELF).await?);
     |                                      ^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `send_msg` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3928:30
     |
3928 |             msg.id = context.send_msg(chat_id, msg).await?;
     |                              ^^^^^^^^ help: there is a method with a similar name: `send_sync_msg`

error[E0061]: this method takes 1 argument but 3 arguments were supplied
    --> src/chat.rs:3929:21
     |
3929 |             context.emit_event(DC_EVENT_MSGS_CHANGED, chat_id, msg.id).await;
     |                     ^^^^^^^^^^                        -------  ------ unexpected argument
     |                                                       |
     |                                                       unexpected argument of type `ChatId`
     |
note: method defined here
    --> src/context.rs:595:12
     |
595  |     pub fn emit_event(&self, event: EventType) {
     |            ^^^^^^^^^^        ----------------
help: remove the extra arguments
     |
3929 -             context.emit_event(DC_EVENT_MSGS_CHANGED, chat_id, msg.id).await;
3929 +             context.emit_event(DC_EVENT_MSGS_CHANGED).await;
     |

error[E0277]: `()` is not a future
    --> src/chat.rs:3929:72
     |
3929 |             context.emit_event(DC_EVENT_MSGS_CHANGED, chat_id, msg.id).await;
     |                                                                       -^^^^^
     |                                                                       ||
     |                                                                       |`()` is not a future
     |                                                                       help: remove the `.await`
     |
     = help: the trait `futures::Future` is not implemented for `()`, which is required by `(): std::future::IntoFuture`
     = note: () must be a future or must implement `IntoFuture` to be awaited
     = note: required for `()` to implement `std::future::IntoFuture`

error[E0599]: no method named `sql_execute` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3933:23
     |
3933 |     q3 = Some(context.sql_execute("DELETE FROM chats_contacts WHERE chat_id=? AND contact_id=?;", (chat_id, contact_id)).await?);
     |                       ^^^^^^^^^^^ method not found in `&Context`

error[E0061]: this method takes 1 argument but 3 arguments were supplied
    --> src/chat.rs:3935:13
     |
3935 |     context.emit_event(DC_EVENT_CHAT_MODIFIED, chat_id, 0).await;
     |             ^^^^^^^^^^                         -------  - unexpected argument of type `{integer}`
     |                                                |
     |                                                unexpected argument of type `ChatId`
     |
note: method defined here
    --> src/context.rs:595:12
     |
595  |     pub fn emit_event(&self, event: EventType) {
     |            ^^^^^^^^^^        ----------------
help: remove the extra arguments
     |
3935 -     context.emit_event(DC_EVENT_CHAT_MODIFIED, chat_id, 0).await;
3935 +     context.emit_event(DC_EVENT_CHAT_MODIFIED).await;
     |

error[E0277]: `()` is not a future
    --> src/chat.rs:3935:60
     |
3935 |     context.emit_event(DC_EVENT_CHAT_MODIFIED, chat_id, 0).await;
     |                                                           -^^^^^
     |                                                           ||
     |                                                           |`()` is not a future
     |                                                           help: remove the `.await`
     |
     = help: the trait `futures::Future` is not implemented for `()`, which is required by `(): std::future::IntoFuture`
     = note: () must be a future or must implement `IntoFuture` to be awaited
     = note: required for `()` to implement `std::future::IntoFuture`

error[E0599]: no method named `sql_free` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3941:17
     |
3941 |         context.sql_free(q3).await;
     |                 ^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `chat_unref` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3943:13
     |
3943 |     context.chat_unref(chat).await;
     |             ^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `contact_unref` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3944:13
     |
3944 |     context.contact_unref(contact).await;
     |             ^^^^^^^^^^^^^ method not found in `&Context`

error[E0599]: no method named `msg_unref` found for reference `&context::Context` in the current scope
    --> src/chat.rs:3945:13
     |
3945 |     context.msg_unref(msg).await;
     |             ^^^^^^^^^ method not found in `&Context`

error[E0061]: this method takes 1 argument but 3 arguments were supplied
    --> src/chat.rs:3929:21
     |
3929 |             context.emit_event(DC_EVENT_MSGS_CHANGED, chat_id, msg.id).await;
     |                     ^^^^^^^^^^                        -------  ------ unexpected argument
     |                                                       |
     |                                                       unexpected argument of type `chat::ChatId`
     |
note: method defined here
    --> src/context.rs:595:12
     |
595  |     pub fn emit_event(&self, event: EventType) {
     |            ^^^^^^^^^^        ----------------
help: remove the extra arguments
     |
3929 -             context.emit_event(DC_EVENT_MSGS_CHANGED, chat_id, msg.id).await;
3929 +             context.emit_event(DC_EVENT_MSGS_CHANGED).await;
     |

error[E0061]: this method takes 1 argument but 3 arguments were supplied
    --> src/chat.rs:3935:13
     |
3935 |     context.emit_event(DC_EVENT_CHAT_MODIFIED, chat_id, 0).await;
     |             ^^^^^^^^^^                         -------  - unexpected argument of type `{integer}`
     |                                                |
     |                                                unexpected argument of type `chat::ChatId`
     |
note: method defined here
    --> src/context.rs:595:12
     |
595  |     pub fn emit_event(&self, event: EventType) {
     |            ^^^^^^^^^^        ----------------
help: remove the extra arguments
     |
3935 -     context.emit_event(DC_EVENT_CHAT_MODIFIED, chat_id, 0).await;
3935 +     context.emit_event(DC_EVENT_CHAT_MODIFIED).await;
     |

Some errors have detailed explanations: E0061, E0252, E0255, E0277, E0425, E0599.
For more information about an error, try `rustc --explain E0061`.
warning: `deltachat` (lib) generated 3 warnings
error: could not compile `deltachat` (lib) due to 38 previous errors; 3 warnings emitted
warning: build failed, waiting for other jobs to finish...
warning: `deltachat` (lib test) generated 3 warnings (3 duplicates)
error: could not compile `deltachat` (lib test) due to 38 previous errors; 3 warnings emitted
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

