Fail
file path is :
projects/deltachat-core/rust/src/contact.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error[E0252]: the name `bail` is defined multiple times
  --> src/contact.rs:14:14
   |
5  | use anyhow::{bail, Result};
   |              ---- previous import of the macro `bail` here
...
14 | use anyhow::{bail, ensure, Context as _, Result};
   |              ^^^^--
   |              |
   |              `bail` reimported here
   |              help: remove unnecessary import
   |
   = note: `bail` must be defined only once in the macro namespace of this module

error[E0252]: the name `Result` is defined multiple times
  --> src/contact.rs:14:42
   |
5  | use anyhow::{bail, Result};
   |                    ------ previous import of the type `Result` here
...
14 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^ `Result` reimported here
   |
   = note: `Result` must be defined only once in the type namespace of this module

error[E0252]: the name `sql` is defined multiple times
  --> src/contact.rs:43:18
   |
4  | use crate::sql::{self, sqlite3_prepare};
   |                  ---- previous import of the module `sql` here
...
43 | use crate::sql::{self, params_iter};
   |                  ^^^^--
   |                  |
   |                  `sql` reimported here
   |                  help: remove unnecessary import
   |
   = note: `sql` must be defined only once in the type namespace of this module

error[E0432]: unresolved import `deltachat_contact_tools::ContactId`
 --> src/contact.rs:6:5
  |
6 | use deltachat_contact_tools::ContactId;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `ContactId` in the root

error[E0432]: unresolved import `crate::sql::sqlite3_prepare`
 --> src/contact.rs:4:24
  |
4 | use crate::sql::{self, sqlite3_prepare};
  |                        ^^^^^^^^^^^^^^^ no `sqlite3_prepare` in `sql`

error[E0425]: cannot find value `DC_CONTEXT_MAGIC` in this scope
    --> src/contact.rs:1264:57
     |
1264 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                                                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CONTACT_ID_LAST_SPECIAL` in this scope
    --> src/contact.rs:1264:91
     |
1264 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0433]: failed to resolve: could not find `Step` in `rusqlite`
    --> src/contact.rs:1271:59
     |
1271 |     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
     |                                                           ^^^^ could not find `Step` in `rusqlite`
     |
help: consider importing one of these items
     |
4    + use core::iter::Step;
     |
4    + use std::iter::Step;
     |
help: if you import `Step`, refer to it directly
     |
1271 -     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
1271 +     if sqlite3_step(&stmt.as_mut().unwrap()) != Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
     |

error[E0433]: failed to resolve: could not find `Step` in `rusqlite`
    --> src/contact.rs:1279:59
     |
1279 |     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
     |                                                           ^^^^ could not find `Step` in `rusqlite`
     |
help: consider importing one of these items
     |
4    + use core::iter::Step;
     |
4    + use std::iter::Step;
     |
help: if you import `Step`, refer to it directly
     |
1279 -     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
1279 +     if sqlite3_step(&stmt.as_mut().unwrap()) != Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
     |

error[E0433]: failed to resolve: could not find `Step` in `rusqlite`
    --> src/contact.rs:1286:59
     |
1286 |     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Done {
     |                                                           ^^^^ could not find `Step` in `rusqlite`
     |
help: consider importing one of these items
     |
4    + use core::iter::Step;
     |
4    + use std::iter::Step;
     |
help: if you import `Step`, refer to it directly
     |
1286 -     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Done {
1286 +     if sqlite3_step(&stmt.as_mut().unwrap()) != Step::Done {
     |

error[E0425]: cannot find value `DC_EVENT_CONTACTS_CHANGED` in this scope
    --> src/contact.rs:1290:24
     |
1290 |     context.emit_event(DC_EVENT_CONTACTS_CHANGED);
     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

warning: unused imports: `Result`, `bail`
  --> src/contact.rs:14:14
   |
14 | use anyhow::{bail, ensure, Context as _, Result};
   |              ^^^^                        ^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:6:5
   |
6  |     unused,
   |     ^^^^^^
   = note: `#[warn(unused_imports)]` implied by `#[warn(unused)]`

warning: unused import: `self`
  --> src/contact.rs:43:18
   |
43 | use crate::sql::{self, params_iter};
   |                  ^^^^

error[E0599]: no method named `is_null_or_invalid` found for reference `&context::Context` in the current scope
    --> src/contact.rs:1264:16
     |
1264 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                ^^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0609]: no field `magic` on type `&context::Context`
    --> src/contact.rs:1264:48
     |
1264 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || contact_id <= DC_CONTACT_ID_LAST_SPECIAL {
     |                                                ^^^^^ unknown field
     |
     = note: available field is: `inner`
     = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `generating_key_mutex`, `oauth2_mutex` ... and 17 others

error[E0425]: cannot find function `sqlite3_step` in this scope
    --> src/contact.rs:1271:8
     |
1271 |     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
     |        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_step` in this scope
    --> src/contact.rs:1279:8
     |
1279 |     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Row || stmt.as_mut().unwrap().column_int(0)? >= 1 {
     |        ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_step` in this scope
    --> src/contact.rs:1286:8
     |
1286 |     if sqlite3_step(&stmt.as_mut().unwrap()) != rusqlite::Step::Done {
     |        ^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0252, E0425, E0432, E0433, E0599, E0609.
For more information about an error, try `rustc --explain E0252`.
warning: `deltachat` (lib) generated 2 warnings
error: could not compile `deltachat` (lib) due to 16 previous errors; 2 warnings emitted
warning: build failed, waiting for other jobs to finish...
warning: `deltachat` (lib test) generated 2 warnings (2 duplicates)
error: could not compile `deltachat` (lib test) due to 16 previous errors; 2 warnings emitted
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

